### ISSUE TITLE
Pixiv 增强 下载不了gif图片

### ISSUE THREAD

**Issue by AmelieNet** [Ahaochan/Tampermonkey#10]
自从pixiv网站更新后就下载不了动图了

**Comment by Ahaochan** [comment]
请更新脚本到0.2.2+

**Comment by AmelieNet** [comment]
额,能下载gif类型的图片吗?

**Comment by Ahaochan** [comment]
@AmelieNet 
目前只支持下载gif的帧图压缩包，需要自己下载后手动合成gif，研究过一段时间用js合成gif无果

**Comment by Ahaochan** [comment]
@AmelieNet 现已支持自动合成gif
