### ISSUE TITLE
pixiv打开多图会卡死无法使用

### ISSUE THREAD

**Issue by cero-ss** [Ahaochan/Tampermonkey#11]
### 脚本的名称及greasyfork链接
- 名称:Pixiv 增强
- greasyfork链接:https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback

### 我确认我已经完成以下步骤

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均未发现相似问题
### 重现步骤
1. 
2. 
3.

**Comment by Ahaochan** [comment]
正在修复中

**Comment by Ahaochan** [comment]
已解决，请更新到0.2.5+
