### ISSUE TITLE
.png格式图片的zip包解压出的图片无法打开

### ISSUE THREAD

**Issue by furcats** [Ahaochan/Tampermonkey#12]
### 脚本的名称及greasyfork链接
- 名称: pixiv plus
- greasyfork链接: https://greasyfork.org/en/scripts/34153-pixiv-plus

### 我确认我已经完成以下步骤

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均未发现相似问题

### 预期行为
解压出的图片可以打开

### 实际行为
无法打开

### 重现步骤
1. 多张图片打包成zip包下载
2. 解压zip包（用的是winrar，提示存在安全隐患）
3. 图片文件无法打开，损坏

### 其他信息
可能是打包出了问题

**Comment by Ahaochan** [comment]
1. 请先测试下这个链接[65424837](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=65424837)是否可以下载并成功打开
2. 如果此链接可以下载并打开成功, 请提供你下载的作品地址链接
3. 如果此链接可以下载但是打开失败, 请尝试使用其他压缩软件, 如: [bandizip](https://cn.bandisoft.com/bandizip/), 如果还是不行, 请提供你下载的作品地址链接

**Comment by furcats** [comment]
用bandizip也无法成功打开从提供连接下载的zip包。0.0

**Comment by Ahaochan** [comment]
@furcats 奇怪了。我这里可以打开的，提供下你的浏览器和插件，我的是Chrome+Tampermonkey

**Comment by furcats** [comment]
@Ahaochan Microsoft Edge + Tampermonkey。

**Comment by Ahaochan** [comment]
@furcats 这种非主流的浏览器就不要用啦。。。新时代的ie，精力有限，只适配chrome和firefox

**Comment by furcats** [comment]
[cid:image005.png@01D4325B.6B0D8D50][cid:image006.png@01D4325B.6B0D8D50]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by furcats** [comment]
@Ahaochan 嗯呐。谢谢。
