### ISSUE TITLE
问卷调查验证码

### ISSUE THREAD

**Issue by XmJwit** [Ahaochan/Tampermonkey#13]
问卷星 自动随机填写: https://greasyfork.org/zh-CN/scripts/369392
当同一IP提交次数超过4次即需填验证码，我找到一种方案解决https://github.com/Blanknesses/proxy_wjx
恳请大佬更新脚本(◍ ´꒳` ◍)

**Comment by Ahaochan** [comment]
>Browsers will not let you set a different proxy server for XHR requests

[is-it-possible-to-use-a-proxy-with-ajax](https://stackoverflow.com/questions/11503641/is-it-possible-to-use-a-proxy-with-ajax)中提到, 浏览器不允许用xhr设置代理服务。

你所提供的方案基于`NodeJS`, 是一种服务端的处理方案, 油猴脚本是一种客户端的处理方案, 受限于浏览器。
