### ISSUE TITLE
你好，可不可以写个适用于所有单选题和多选题的随机选择呢？

### ISSUE THREAD

**Issue by gqzc** [Ahaochan/Tampermonkey#14]
类似于这样的扩展，但是这个扩展的作者联系不到了，在很多网站不起作用，所以求助于您
https://chrome.google.com/webstore/detail/cdhihojoekiijkcmfdejobiodnlgijmb

**Comment by Ahaochan** [comment]
能力有限，做不到desu~

**Comment by gqzc** [comment]
额，那你的那个问卷星脚本怎样自己添加其他的网址呢？
