### ISSUE TITLE
Pixiv搜索页部分信息缺失

### ISSUE THREAD

**Issue by HashLiver** [Ahaochan/Tampermonkey#16]
### 脚本的名称及greasyfork链接
- 名称:Pixiv 增强 0.40
- greasyfork链接:https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus
### 我确认我已经完成以下步骤

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均未发现相似问题

### 预期行为
开启脚本前：
![pixiv 2018 10 19](https://user-images.githubusercontent.com/42889797/47213544-efd0e000-d3cd-11e8-9e9e-6fe336908924.png)

### 实际行为
开启脚本后：
![pixiv 2018 10 19 02](https://user-images.githubusercontent.com/42889797/47213557-fbbca200-d3cd-11e8-8628-eb91672bac25.png)

### 重现步骤
确认只是脚本问题，并没有uBlock Origin的干扰。

### 其他信息
浏览器：Chrome 70.0.3538.67

**Comment by Ahaochan** [comment]
已解决, 请更新到0.4.1+
解决方案: [Line 815](https://github.com/Ahaochan/Tampermonkey/blob/8f06e9416f6eff1745522fe2277e9bc8f0c3c268/Pixiv%20%E5%A2%9E%E5%BC%BA.user.js#L815)添加`[data-src]`限制
