### ISSUE TITLE
帮忙随机填下问卷星问卷调查，甚是感谢！问卷地址：https://www.wjx.cn/jq/31206581.aspx

### ISSUE THREAD

**Issue by zxao** [Ahaochan/Tampermonkey#17]
### 脚本的名称及greasyfork链接
- 名称:
- greasyfork链接:

### 我确认我已经完成以下步骤

- [] 我确认除了此脚本外, 其他任意脚本能正常运行
- [] 我确认此脚本是最新版本
- [] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均未发现相似问题

### 重现步骤
1. 
2. 
3.

**Comment by Ahaochan** [comment]
自己填，评分题暂不适配，有空会适配

**Comment by zxao** [comment]
好的，感谢

    
        
            
                
                    
                        
                    
                    
                        
                            962585363
                            
                            
                                
                                    邮箱：962585363@qq.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年12月21日 17:49，Ahaochan 写道： 自己填，评分题暂不适配，有空会适配

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ahaochan/Tampermonkey","title":"Ahaochan/Tampermonkey","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ahaochan/Tampermonkey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ahaochan in #17: 自己填，评分题暂不适配，有空会适配"}],"action":{"name":"View Issue","url":"https://github.com/Ahaochan/Tampermonkey/issues/17#issuecomment-449336663"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ahaochan/Tampermonkey/issues/17#issuecomment-449336663",
"url": "https://github.com/Ahaochan/Tampermonkey/issues/17#issuecomment-449336663",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ahaochan** [comment]
已不再维护此脚本
