### ISSUE TITLE
p站插件能更新一个左右键翻页的功能吗？找图的时候很麻烦，谢谢dalao了

### ISSUE THREAD

**Issue by EnderMagic** [Ahaochan/Tampermonkey#18]
### 脚本的名称及greasyfork链接
- 名称:
- greasyfork链接:

### 我确认我已经完成以下步骤

- [] 我确认除了此脚本外, 其他任意脚本能正常运行
- [] 我确认此脚本是最新版本
- [] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均未发现相似问题

### 重现步骤
1. 
2. 
3.

**Comment by Ahaochan** [comment]
P站自带左右键翻页功能
为了适配这个功能，我还研究了下MutationObserver咋用。
比如打开这个[链接](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=71005633), 然后按方向键→, 即可查看下一个图片。
