### ISSUE TITLE
Feature request for Pixiv Plus

### ISSUE THREAD

**Issue by Anyrainel** [Ahaochan/Tampermonkey#19]
我觉得有几个功能自己很想要，而且也可以帮忙实现（如果可行的话）。
1."See all" button直接在当前页面展示所有图片。两个设计：1a. 直接按顺序排下去 1b.保持原来大小，做个内嵌的滚动。
2. 一键添加/去除bookmark。这个功能可能不适合所有用户，不知道有没有办法加个preference。
3. 在看大图的模式加个向左和向右按键直接翻页。

想听一下你的意见，以及如果需要帮助的话给一些pointers.

**Comment by Ahaochan** [comment]
1. 仙尊的有实现，可以参考下，这个功能我觉得没必要，当然你也可以做。
2. bookmark我没了解过是干嘛用的
3. 获取相邻的作品可以使用我封装的`illust()`函数或者使用`window.globalInitData`变量获取响应的数据。

如果提`pull request`, 注意将自己的代码用 `(function(){})()`的形式包裹起来, 还有就是本脚本使用了大量的`MutationObserver`监听元素变化, 小心不要让页面卡死。

**Comment by Anyrainel** [comment]
bookmark就是💗，中文是收藏？

**Comment by Tsuk1ko** [comment]
> 我觉得有几个功能自己很想要，而且也可以帮忙实现（如果可行的话）。
> 1."See all" button直接在当前页面展示所有图片。两个设计：1a. 直接按顺序排下去 1b.保持原来大小，做个内嵌的滚动。
> 2. 一键添加/去除bookmark。这个功能可能不适合所有用户，不知道有没有办法加个preference。
> 3. 在看大图的模式加个向左和向右按键直接翻页。
> 
> 想听一下你的意见，以及如果需要帮助的话给一些pointers.

很巧，第一个功能P站帮你实现了……在几天前改版了，但是大图模式变成了点向上和向下翻页

这导致一个新的问题，原来脚本中的自动加载原图会导致把当前页内展示的所有图片的地址都替换成第一个图片的原图地址，望修复 @Ahaochan

**Comment by Ahaochan** [comment]
[65424837](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=65424837)页面无法复现描述, 请提供出现bug的链接以及重现步骤. @Tsuk1ko

**Comment by Ahaochan** [comment]
残念，大概我又是未被神选中之人。
这大概是`beta`功能，只有部分用户可以看见，以前也出现过这种情况，等待功能正式上线再进行适配吧。
![image](https://user-images.githubusercontent.com/17980786/55138660-f890c380-516e-11e9-920e-1a85486618c3.png)

**Comment by Tsuk1ko** [comment]
原来是这样……好的

**Comment by Ahaochan** [comment]
残念，大概我又是未被神选中之人。
这大概是`beta`功能，只有部分用户可以看见，以前也出现过这种情况，等待功能正式上线再进行适配吧。
![image](https://user-images.githubusercontent.com/17980786/55138660-f890c380-516e-11e9-920e-1a85486618c3.png)
@Tsuk1ko

**Comment by ShimotsukiH** [comment]
反馈 同样遇到相同问题

**Comment by Ahaochan** [comment]
@Tsuk1ko @ShimotsukiH 请更新到0.5.7+

**Comment by Tsuk1ko** [comment]
已正常，感谢修复

**Comment by Ahaochan** [comment]
@Anyrainel 
目前官方已经支持了一键添加收藏的功能，关闭`issue`，若有需要，请`reopen`
