### ISSUE TITLE
在课程列表触发原有登录dialog, 避免新开窗口登录

### ISSUE THREAD

**Issue by ivoth** [Ahaochan/Tampermonkey#2]
在课程列表触发原有登录dialog, 避免新开窗口登录,同时登录完是会自动刷新本页面的
$('#js-signin-btn').trigger('click');

**Comment by Ahaochan** [comment]
`$('#js-signin-btn').trigger('click');`不管用。。。。，可能慕课网不是通过jquery注入点击事件的，在stackoverflow找到原生模拟点击的例子，修改如下。
```
$('#downTip').click(function(){
            var clickEvent  = document.createEvent ('MouseEvents');
            clickEvent.initEvent ('click', true, true);
            document.getElementById('js-signin-btn').dispatchEvent (clickEvent);
});
```

**Comment by ivoth** [comment]
原因是发生了跨域调用,所以没反应....
我是在Console中调用的,发现是可以. 谁知道在油猴中脚本是跨域了,不熟悉油猴的环境

**Comment by ivoth** [comment]
搜了一下,的确是执行环境的不同导致的,然后找到了另一个执行方法
http://stackoverflow.com/questions/1622145/how-can-i-mimic-greasemonkey-firefoxs-unsafewindow-functionality-in-chrome
执行`location.href="javascript:$('#js-signin-btn').click()";`即可同样调起登录dialog
