### ISSUE TITLE
Pixiv增强 旧版GM API问题

### ISSUE THREAD

**Issue by sakuyaa** [Ahaochan/Tampermonkey#21]
由于我使用的是火狐上的暴力猴，目前还无法支持GM4的API，脚本用到了`https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js`来适配旧版GM API，我看到`https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html`里面说的，适配GM4和GM3需要同时grant新旧API
但是脚本grant元数据只列出了GM4的API，导致暴力猴无法正常工作，麻烦增加下旧版API的grant

**Comment by Ahaochan** [comment]
我之前有尝试使用`polyfill`来兼容`GM3`, 但是没有成功.
如果可以, 你可以提供一个简单的代码块`demo`吗?

**Comment by sakuyaa** [comment]
我试了下，增加以下grant就可以了
```
// @grant       GM_xmlHttpRequest
// @grant       GM_setClipboard
// @grant       GM_setValue
// @grant       GM_getValue
```

**Comment by Ahaochan** [comment]
可以了, 请更新到0.5.4+
