### ISSUE TITLE
首頁右側廣告去除後不對齊

### ISSUE THREAD

**Issue by partment** [Ahaochan/Tampermonkey#22]
![firefox_2019-02-25_02-15-33](https://user-images.githubusercontent.com/5278061/53302639-bc362300-38a3-11e9-9391-d9d954bdc690.png)
用這行代碼來改善此問題
`$("#column-misc section:nth-child(2)").css({"margin-top":"0px"});`

**Comment by Ahaochan** [comment]
已修复
