### ISSUE TITLE
问卷星自动填写可以添加代码设置每个题选项有规律性吗？

### ISSUE THREAD

**Issue by YN-G** [Ahaochan/Tampermonkey#25]
问卷星自动填写可以添加代码设置每个题选项有规律性吗？就是每个题目哪个选项概率大概为多少自动填写

**Comment by Ahaochan** [comment]
https://github.com/Ahaochan/Tampermonkey/blob/master/%E9%97%AE%E5%8D%B7%E6%98%9F%20%E8%87%AA%E5%8A%A8%E9%9A%8F%E6%9C%BA%E5%A1%AB%E5%86%99.user.js#L46-L51
参考这部分代码

**Comment by YN-G** [comment]
我尝试了这个代码，但设置以后整份问卷就都不能自动填写了，可能我自己实在太无知了，不过还是很谢谢您了，麻烦您了




------------------ 原始邮件 ------------------
发件人: "Ahaochan"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 上午9:39
收件人: "Ahaochan/Tampermonkey"<Tampermonkey@noreply.github.com>;
抄送: "1028483178"<1028483178@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Ahaochan/Tampermonkey] 问卷星自动填写可以添加代码设置每个题选项有规律性吗？ (#25)




https://github.com/Ahaochan/Tampermonkey/blob/master/%E9%97%AE%E5%8D%B7%E6%98%9F%20%E8%87%AA%E5%8A%A8%E9%9A%8F%E6%9C%BA%E5%A1%AB%E5%86%99.user.js#L46-L51
 参考这部分代码
