### ISSUE TITLE
Pixiv增强无法通过更改设置关闭图片尺寸显示

### ISSUE THREAD

**Issue by ztllllll** [Ahaochan/Tampermonkey#28]
### 基本信息 

- 版本号: 0.6.1
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [x] Other  waterfox56.2.13 64 位(不知道这个能不能算火狐...)
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)4.9.5941
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
在用户设置-pixiv增强设置选项内去掉显示图片尺寸大小的勾选后，刷新图片页面不会再在右上角显示尺寸。

### 实际行为 
在用户设置-pixiv增强设置选项内去掉显示图片尺寸大小的勾选后，刷新图片页面依旧在右上角显示尺寸。

### 重现步骤 
1. 进入pixiv用户设置。
2. 取消勾选显示图片尺寸大小，并点击保存。
3. 刷新图片页，仍在右上角显示尺寸。

### 其他信息 
无

**Comment by Ahaochan** [comment]
请更新到0.6.3+
显示尺寸的按钮忘了适配多图和单图了
