### ISSUE TITLE
P站更新了图片的网址格式，求插件更新

### ISSUE THREAD

**Issue by JiangYouJun** [Ahaochan/Tampermonkey#30]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [x] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 实际行为 
https://www.pixiv.net/artworks/76967940
p站更新了每个图片的网站格式，现在看图片插件好像就不奏效了QAQ

### 重现步骤 
1. 
2. 
3.

**Comment by Ahaochan** [comment]
已修复 #29
