### ISSUE TITLE
搜索栏下方的【收藏人数】栏失效了

### ISSUE THREAD

**Issue by FFR41Mave** [Ahaochan/Tampermonkey#33]
你好，搜索栏下方的【收藏人数】栏失效了，选择对应人数后无法搜索。

**Comment by Ahaochan** [comment]
`users入り`的方式似乎已被官方封杀, 如有好的搜索想法, 可以提`issue`

**Comment by Ahaochan** [comment]
`users入り`的搜索方式似乎又复活了
请更新到0.7.6
