### ISSUE TITLE
Recommended followers list no longer working (not sure if site update is the reason or not)

### ISSUE THREAD

**Issue by ajtpak** [Ahaochan/Tampermonkey#36]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [X] Other   Vivaldi version 2.5.1525.48 Windows 10
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
The expected behavior should be shown recommended artists after following a new artist. Not sure if this is a pixiv site update issue or github extension issue

### 实际行为 
When following a new artist, nothing else happens afterwards. It doesn't display a box of recommended artists when it should.

### 重现步骤 
1. Follow an artist
2. No "suggestions" artists tab shows up afterwords
3. 

### 其他信息  

I only have the pixiv plus extension running on Pixiv. No other extensions are running on that website. I did not run into this issue until after the site updated.

**Comment by Ahaochan** [comment]
@ajtpak 
I have never used this feature.
After I disabled The Tampermonkey UserScript Extension, I can't look suggestions.
Can you provide screenshots?

**Comment by ajtpak** [comment]
Well I can provide a screenshot on mobile since the desktop version doesn't work. What should happen when you follow an artist is a recommendation window like so. And with the extension, when you follow a new artist or look at one of the recommendations, the recommendation window doesn't go away. However when you use the recommendation window without your extension, whenever you would follow an artist or go to any of the recommended art, the recommendations window would disappear.

Below is the example of what should happen after you follow an artist. But again, I'm not sure if this is because of a site update (I hope not) or not. So I hope I'm not wasting your time with this or anything. 
![example](https://user-images.githubusercontent.com/8887956/72546192-54405080-3858-11ea-861f-d5c7ce43ea11.png)

**Comment by Ahaochan** [comment]
![image](https://user-images.githubusercontent.com/17980786/72582157-d2662b00-391c-11ea-8466-c383ccc577cd.png)
![image](https://user-images.githubusercontent.com/17980786/72582168-da25cf80-391c-11ea-80e9-727706d00688.png)

I can look The `recommendation window` after I follow a new artist.
So, Can you try run this script in Chrome?
I only support Chrome And Firefox Because I don't have enough time to support other Browser.

**Comment by ajtpak** [comment]
Yep, it works on chrome. I figured out the issue though. I feel like an idiot, it seemed to be something on ublock origin's end. After turning that off it worked. My apologies for wasting your time, and thank you for helping me out.
