### ISSUE TITLE
网站顶部的空白字段

### ISSUE THREAD

**Issue by MiTereKun** [Ahaochan/Tampermonkey#37]
我认为这是你在没有此主题的情况下将做出的最接近的修复，但以防万一。
由于其他按钮均已及时移至左侧菜单，因此我认为这只是一个遗漏。
![image](https://user-images.githubusercontent.com/32958490/73449650-628d8100-43af-11ea-94c0-dfd6e7197e53.png)
哦，我认为还有另一个与校长的评论有关的错误 https://www.pixiv.net/artworks/77557336?comment_id=96661042 - 下 =(

也许做一个单独的设置 向上移动 “<div class = _2BF9Y8h” 那很方便...
![image](https://user-images.githubusercontent.com/32958490/73451328-193f3080-43b3-11ea-8c3f-88fe327033e8.png)
- 具体来说，此功能是在设置中激活的，而不是默认情况下。

非常感谢您的工作! 未经您的许可，我不知道如何使用该网站，哈哈
这是不好的，pixiv现在看起来像一个谷歌服务

**Comment by Ahaochan** [comment]
Hi, If you speak English, please talk English. Don't use translation Chinese.

The Pixiv changed their style again. Please wait The userscript update.

**Comment by MiTereKun** [comment]
нет не говорю, Мне хоть так, хоть так надо всё переводить.
Раньше обратный перевод получался на много хуже, по этому уже год как перестал оставлять оригинал текста

И я знаю, что обновление выйдет, спасибо вам за это. Но только я написал ещё 2 вещи

**Comment by Ahaochan** [comment]
emmm... some hard...
I try to repeat your meaning.

1. The div `class=sc-LzMgz ktQBVr` is a useful element, I hide it by mistake.
2. The [url](https://www.pixiv.net/artworks/77557336?comment_id=96661042) can not auto show all comment. 

right?
