### ISSUE TITLE
使用Pixiv增强时很容易触发403错误

### ISSUE THREAD

**Issue by lychichem** [Ahaochan/Tampermonkey#38]
### 基本信息 

- 版本号: 79.0.309.71
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [x] Other Microsoft Edge 
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
能正常加载图片

### 实际行为 
加载图片的错误率变高，在控制台看到报大量失败，直接访问图片地址报403.关闭脚本后正常。

### 重现步骤 
1. 安装Edge（chromium内核）
2. 安装Tampermonkey
3. 安装脚本
4. 访问一些pixiv页面

### 其他信息 
不确定是否网络相关，我这里贴下我网络信息，50M电信宽带，ss用的jms，附加obfs，但pac对pixiv图片地址不启用，确认直连能正确解析到pixiv图片服务器ip，浏览器控制台显示的加载错误内容类型全为png或svg

**Comment by Ahaochan** [comment]
精力有限，目前只维护`Chrome + Tampermonkey`。
`403`我怀疑是没有携带refer的问题，没用过`Microsoft Edge`，建议看看网络请求。
