### ISSUE TITLE
使用新版edge，其他插件可用，使用此插件编辑pixiv收藏会出现bug，显示多个收藏图片并且实际上无法编辑

### ISSUE THREAD

**Issue by NextFutureOfficial** [Ahaochan/Tampermonkey#41]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [] 我确认除了此脚本外, 其他任意脚本能正常运行
- [] 我确认此脚本是最新版本
- [] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 重现步骤 
1. 
2. 
3.

**Comment by Ahaochan** [comment]
请更新到0.7.8
