### ISSUE TITLE
该Pixiv 增强脚本与PixivBatchDownloader扩展程序冲突

### ISSUE THREAD

**Issue by catyue** [Ahaochan/Tampermonkey#43]
您好，经过排查，在同时开启PixivBatchDownloader扩展与Pixiv 增强脚本（本人使用暴力猴脚本扩展）之后，pixiv首页顶栏（或者说页眉）会由这个样子
![image](https://user-images.githubusercontent.com/23721173/75947775-85deab00-5edc-11ea-8232-e68f224648a0.png)
恢复成原来的
![image](https://user-images.githubusercontent.com/23721173/75947859-bd4d5780-5edc-11ea-93c4-60b2f6e1211c.png)
这个样子
[PixivBatchDownloader](https://chrome.google.com/webstore/detail/powerful-pixiv-downloader/dkndmhgdcmjdmkdonmbgjpijejdcilfh)扩展程序地址如下，使用的人也挺多
您看是否有解决冲突的必要？

**Comment by catyue** [comment]
对方给出了了[解决方法](https://github.com/xuejianxianzun/PixivBatchDownloader/issues/61#issuecomment-595034810)，个人测试可以解决问题，您考虑一下合并PR。

**Comment by Ahaochan** [comment]
已合并PR，感谢你的提交:)
