### ISSUE TITLE
那个直接搜索热门用不了力

### ISSUE THREAD

**Issue by guangyu233** [Ahaochan/Tampermonkey#45]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [] 我确认除了此脚本外, 其他任意脚本能正常运行
- [] 我确认此脚本是最新版本
- [] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 重现步骤 
1. 
2. 
3.

**Comment by Ahaochan** [comment]
无法复现，请提供必要信息。

**Comment by hismyth** [comment]
> 无法复现，请提供必要信息。

你好，请问我有问卷星问卷的题目的题库，如何让他按照题库里的答案自动填写呢，谢谢

**Comment by Ahaochan** [comment]
@hismyth 代码中有对应固定答案的注释后的代码，请自行CV大法

**Comment by hismyth** [comment]
您好，我最开始粗略地的看了下代码注释，您是说那个&nbsp; 为..问卷匹配&nbsp; 那个注释吗？我现在看不了代码不能很理解您这个回答的意思，明天我会看一看，谢谢。


 
---原始邮件---
发件人: "Ahaochan"<notifications@github.com&gt;
发送时间: 2020年4月8日(星期三) 晚上8:00
收件人: "Ahaochan/Tampermonkey"<Tampermonkey@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"hismyth"<1198358678@qq.com&gt;;
主题: Re: [Ahaochan/Tampermonkey] 那个直接搜索热门用不了力 (#45)




 
@hismyth 代码中有对应固定答案的注释后的代码，请自行CV大法

**Comment by hismyth** [comment]
您好，请问是这个吗？

是吧所有题目和对应的选项以及答案复制到这里面吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ahaochan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 晚上8:00
收件人:&nbsp;"Ahaochan/Tampermonkey"<Tampermonkey@noreply.github.com&gt;;
抄送:&nbsp;"奋发图强"<1198358678@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Ahaochan/Tampermonkey] 那个直接搜索热门用不了力 (#45)





 
@hismyth 代码中有对应固定答案的注释后的代码，请自行CV大法
