### ISSUE TITLE
download/preview enhancement request

### ISSUE THREAD

**Issue by NewUserHa** [Ahaochan/Tampermonkey#46]
1. Can you consider making the file names in the `zip` downloaded by this script like `{pid}-{i}.png` be the same with downloaded by right-clicking on one of the original size images like its `original name` or `{pid}-p{i}.png`?
    And the file timestamp didn't use local time zone info.
2. also in the multi-image artwork pages, for slower connection, it's sometimes very slow to load all images. Can you consider adding a preview window on the page with the `smaller image links` in `src` of their `image tag` in like other scripts to help instantly know what the rest of the images are?

Thanks!

**Comment by Ahaochan** [comment]
Unfortunately, I no longer accept feature development.
