### ISSUE TITLE
Download Ugoira as Animated PNG (APNG)?

### ISSUE THREAD

**Issue by NintendoManiac64** [Ahaochan/Tampermonkey#48]
GIF is limited to 256 colors.

But APNG effectively has no color limit (16bit per channel, so 64bit per pixel including alpha channel or 48bit per pixel without alpha)

And APNG now has very good web browser support: https://caniuse.com/#feat=apng

(the only thing is that an unoptimized APNG can have quite a large file size, and I don't know how realistic it is to support the sort of lossless inter-frame optimization that software like "[APNG Optimizer](https://sourceforge.net/projects/apng/files/APNG_Optimizer/)" implements)

**Comment by Ahaochan** [comment]
Good idea.
I use [`gifjs`](https://jnordberg.github.io/gif.js/) to generate gif.
Have any js library to generate apng?
You can open a new pull request.
