### ISSUE TITLE
china fix

### ISSUE THREAD

**Issue by w5860363** [Ahaochan/Tampermonkey#49]
China blocked https://code.jquery.com/jquery-2.2.4.min.js

// @require     https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js

**Comment by Ahaochan** [comment]
no blocked.

https://ping.chinaz.com/https://code.jquery.com/
https://ping.chinaz.com/https://ajax.aspnetcdn.com/
