### ISSUE TITLE
Width Overflow / 网页宽度溢出

### ISSUE THREAD

**Issue by Cleverambo** [Ahaochan/Tampermonkey#50]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [x] Other  （是 Chromium 84.0.522.44 的 Edge，我觉得这应该能优化一下吧）
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)
- 屏幕分辨率 -
2736×1824 (200 % 缩放）(Surface Pro 6)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 实际行为 
网页宽度超出边界（出现横向滚动条），此时我已经将浏览器窗口最大化
我尝试禁用了其他所有插件和脚本，但是这个问题依然存在

### 其他信息 
![image](https://user-images.githubusercontent.com/36615067/88564766-330db780-d066-11ea-9b4f-6a6b75ad4887.png)

**Comment by Ahaochan** [comment]
https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/discussions/31017
