### ISSUE TITLE
可不可以直接查看全部图片？

### ISSUE THREAD

**Issue by yzs0324** [Ahaochan/Tampermonkey#53]
比如说作者主页和图片合集，能不能不用点「查看全部」就直接显示所有图片？

**Comment by yzs0324** [comment]
顺便问一下怎么关掉图品右上角显示图片尺寸的功能？

**Comment by Ahaochan** [comment]
1. 已修复，请更新到0.8.3+
2. 查看文档说明，https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus
