### ISSUE TITLE
当进入到pixiv的画师页面时，画师介绍的话语会多出来一条。

### ISSUE THREAD

**Issue by yuijker** [Ahaochan/Tampermonkey#54]
### 基本信息 

- 版本号: 0.8.2
- 所用浏览器及版本号: 
  - [x] [Chrome](https://www.google.com/chrome/) 88.0.4324.96
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/) 4.11
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
画师对自己的介绍只有一行且后面的灰字可以点击，可以找到画师对自己的简单介绍。

### 实际行为 
画师介绍的话语会多出来一条，且可以确认上面的介绍的灰字不可点击，证明位于上面的介绍是错误的地方。

### 重现步骤 
1. 在油猴插件里开启脚本
2. 打开pixiv，来到任意画师的主页
3. 此问题出现。

### 其他信息 
不使用脚本时
![image](https://user-images.githubusercontent.com/72558803/108171714-e2ab9380-7136-11eb-838a-d648d48972e3.png)

使用脚本时
![image](https://user-images.githubusercontent.com/72558803/108171815-066ed980-7137-11eb-8aa3-2a727b36f4bf.png)

**Comment by Ahaochan** [comment]
已修复，请更新到0.8.3+
