### ISSUE TITLE
Pixiv增强 能否为"自动加载原图"功能增加开关

### ISSUE THREAD

**Issue by Franinc** [Ahaochan/Tampermonkey#55]
有些作者习惯单画廊放多张大尺寸图片，例如[artworks/73808146](https://www.pixiv.net/artworks/73808146)，一次15张，原图每张大小1-4M。一个画廊就用掉近100M流量实在吃不消😂
默认的master1200:
![1J(G D%$((}BZVBP%TEY@F9](https://user-images.githubusercontent.com/26399054/111920709-6c9aa380-8acb-11eb-9af1-a45992ab193e.png)

**Comment by Ahaochan** [comment]
添加了一个**自动加载多图**的开关，默认开启的，你取消勾选就好了
设置页面地址：https://www.pixiv.net/setting_user.php?success=1
