### ISSUE TITLE
关于视频下载的接口问题

### ISSUE THREAD

**Issue by tangzhe1996** [Ahaochan/Tampermonkey#6]
filename=1-1Linux简介&fileurl=http://v2.mukewang.com/e2683b34-157f-4327-99a3-fec22711ac38/M.mp4?auth_key=1506525763-0-0-7a0c21f2823ae12d07bc2f9875295f5c
视频地址解析出来是这样的，是你说的V2接口了吧？但是我用IDM下载时出错：无法找到服务器

**Comment by Ahaochan** [comment]
v1和v2的接口解析不到DNS服务器，v3可以，可能慕课网关了v1和v2的接口，统一迁移到v3接口，或者也可能是慕课网DNS配置没配好（可能性不大）。
目前正在毕业设计中，暂无力维护脚本。

**Comment by Ahaochan** [comment]
已放弃慕课网视频下载脚本的维护。详情看脚本内的注释说明。
