### ISSUE TITLE
gif下载的时间轴不对

### ISSUE THREAD

**Issue by HongyeY** [Ahaochan/Tampermonkey#60]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [x] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
下载的gif时间轴应该和网页显示效果一致

### 实际行为 
gif下载的时间轴不对，网页上的gif不同帧有不同时长，下载后所有帧时长都相同了

### 重现步骤 
1. 打开https://www.pixiv.net/artworks/49319675
2. 点击gif下载
3.

**Comment by Ahaochan** [comment]
你是否了解gif动图原理？gif不是视频，没有时间轴，本质是以固定频率切换下一帧图片

目前gif解析的数据来源于pixiv，我下载后和网页上对比，并未发现有明显延时差异。
https://www.pixiv.net/ajax/illust/49319675/ugoira_meta?lang=zh

**Comment by HongyeY** [comment]
抱歉过了好久忘记回了。GIF每帧都可以设置delay，无论是在Photoshop的时间轴窗口里里还是网页上(https://www.pixiv.net/ajax/illust/49319675/ugoira_meta?lang=zh)的{"file":"000000.jpg","delay":50}选项里都可以看到这一属性。实际上这张图下载的gif确实和原图有区别。在手机pixiv app上更明显，在下载的gif里，这只猫吃饭的速度明显快了好多。

**Comment by Ahaochan** [comment]
感谢指正，已合并MR
