### ISSUE TITLE
CDN切换

### ISSUE THREAD

**Issue by MiTereKun** [Ahaochan/Tampermonkey#62]
CloudFlare incredibly slow since its nodes are too far from Asia. In addition, the Japan-America optical highways are still heavily congested.
I want to go to the original Japanese ip. From a [neighboring project](https://github.com/DIYgod/RSSHub/issues/5916) I learned that the address [public-api.secure.pixiv.net](https://public-api.secure.pixiv.net/zero) leads to jp ip 210.140.131.220, I wery want to take all the traffic of the site directly as before octabr 2020.
fanbox works on ip 210.140.131.200 and from here the pictures are loaded much faster - the whole problem is in the orange monster
![image](https://user-images.githubusercontent.com/32958490/133173272-1998ad9b-c78d-403a-bb5d-3afda46bab76.png)

**Comment by MiTereKun** [comment]
the last 3 days sometimes writes that the site is generally unavailable and only the "holy" CloudFlare can allow you to access pixiv. 
and then the pages themselves can report that they do not respond and the images are loaded by a minute
![в](https://user-images.githubusercontent.com/32958490/133946957-fd31cf03-b426-4209-aac3-0488a673197e.png)

**Comment by Ahaochan** [comment]
The cdn of this script has been replaced with bootcdn

https://github.com/Ahaochan/Tampermonkey/commit/ee4da87732d9cf335b6707101bf5f1f2a9904caf#diff-cfd7c000ec5f775fa0e7631481ff88046d49f3946daec542ef7a8b789aa76808

**Comment by MiTereKun** [comment]
ваул, у меня в стране заблокировали pixiv (удивительно как этого не произошло раньше) но не заблокировали домен с картинками pximg.net. У меня в браузере стоит плагин для обхода только заблокированных ресурсов, таким образом скорость работы вот вообще не снизилась, и, видимо pximg сломался и перестал считать, что я захожу с европейского ip и внезапно стал сосать картинки непосредственно из Японии и скорость ОЧЕНЬ СИЛЬНО ВЫРОСЛА. Я просто вообще не понимаю, кто придумали такое топорное деление ip адресов, с 2019 года скорость pixiv реально упала как только владельцы связались в горе CloudFlare. Как дже он отвратительно работает во Владивостоке, японский маршрут напрямую через японское море с пингом 49 мс - the best!
