### ISSUE TITLE
搜索增强宽度设置异常

### ISSUE THREAD

**Issue by jimstar06** [Ahaochan/Tampermonkey#64]
### 基本信息 

- 版本号: 0.8.4
- 所用浏览器及版本号: 
  - [ ] [Chrome](https://www.google.com/chrome/)
  - [X] [Firefox](https://www.mozilla.org/en-US/) 94.0.1
  - [X] Edge 95.0.1020.44  
- 插件扩展: 
  - [X] [Tampermonkey](https://tampermonkey.net/)
  - [ ] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [ ] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [X] 我确认除了此脚本外, 其他任意脚本能正常运行
- [X] 我确认此脚本是最新版本
- [X] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
原顶部搜索栏被替换，且保持顶栏原始宽度

### 实际行为 
Firefox、Edge中顶栏宽度增大，右侧元素溢出边界，导致页面可左右拖动。
Firefox中下拉列表宽度设置错误。
Edge表现
![](https://user-images.githubusercontent.com/12005178/141126544-1d0e5e8b-ae44-4450-a8ea-d5a90f31719c.jpg)

Firefox表现
![](https://user-images.githubusercontent.com/12005178/141126604-c3bfa202-0bff-4d3c-9230-70f427d27afe.jpg)

### 重现步骤 
1. 禁用除本脚本外所有pixiv相关脚本及拓展
2. 打开pixiv主页

### 其他信息 
Windows 10 21H1
分辨率 2560x1600 175%缩放

**Comment by popu-web** [comment]
+1

**Comment by Ahaochan** [comment]
已无计划支持除Chrome+Tampermonkey之外的组合，可提PR
