### ISSUE TITLE
下载按钮不显示导致无法点击下载

### ISSUE THREAD

**Issue by LenKiMo** [Ahaochan/Tampermonkey#69]
### 基本信息 

- 版本号: 0.8.3
- 所用浏览器及版本号: 
  - [x] [Chrome](https://www.google.com/chrome/)
  `版本 100.0.4896.12（正式版本）dev （64 位）`
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
`V4.14`

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
打开任意下载页面后，作品下方显示下载按钮。

### 实际行为 
只显示下载进度，但无按钮可点击下载。

### 重现步骤 
1. 升级到 Chrome Dev 100
2. 打开任意多图 Pixiv 页面
3. 

### 其他信息 
![2022-02-28_221141](https://user-images.githubusercontent.com/10625080/155997845-038db16b-800a-4aad-9d4f-b8b93305c390.png)

**Comment by Ahaochan** [comment]
下载按钮本质是拷贝旁边的分享图标，旋转180度，因为你的分享按钮都没有加载出来，自然看不到下载按钮
https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/discussions/119655
