### ISSUE TITLE
自动加载评论失效

### ISSUE THREAD

**Issue by yuijker** [Ahaochan/Tampermonkey#70]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [x] Other  Edge 101.0.1210.39
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/) 4.16
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
开启自动加载评论后，作品下的评论会自动向下加载

### 实际行为 
即使开启自动加载评论后，作品下的评论也不会自动向下加载

### 重现步骤 
1. 安装脚本
2. 来到pixiv的设置页，来确认该功能是否开启
3. 打开一个作品页面，看到评论没有自动加载

### 其他信息 

![image](https://user-images.githubusercontent.com/72558803/167295448-f7f74435-36cc-44a6-a284-0355201328cb.png)

![image](https://user-images.githubusercontent.com/72558803/167295480-b1a8ae76-a060-4b2a-b6de-cecfb3c1289c.png)

**Comment by Ahaochan** [comment]
目前本脚本只维护Chrome+Teampermonkey，欢迎提PR

**Comment by Ahaochan** [comment]
https://github.com/Ahaochan/Tampermonkey/issues/79
