### ISSUE TITLE
希望增加gif保存成mp4功能

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [Ahaochan/Tampermonkey#71]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [ ] [Chrome](https://www.google.com/chrome/)
  - [ ] [Firefox](https://www.mozilla.org/en-US/)
  - [x] CentBrowser 4.3.9.248  
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/)
  - [ ] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [ ] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
Pixiv动图下显示下载为mp4按钮

### 实际行为 
只有下载zip和下载gif

### 重现步骤 
1. 打开动图页面
2. 寻找下载mp4按钮

### 其他信息 
gif图片的体积太大了，很多都接近100M，但打包成mp4后只有10M左右，体积只有十分之一，画质没有任何损耗，因此建议增加此功能，很多B站插件有合并视频分段的功能是用ffmpeg实现的，Pixiv增强也可以使用同样的方案，甚至可以让用户自己选择本地ffmpeg安装目录

**Comment by MiTereKun** [comment]
"apng" or newer formats such as "avif" or already outdated, but still not supported by many anywhere except in google chrome, "webp"

mp4 is just really inconvenient to look in galleries with pictures

**Comment by Misaka-Mikoto-Tech** [comment]
> "apng" or newer formats such as "avif" or already outdated, but still not supported by many anywhere except in google chrome, "webp"
> 
> mp4 is just really inconvenient to look in galleries with pictures

The size of webp is more larger than that of mp4. The mp4 file can be viewed by `potplayer` with single file loop mode. And `Media Preview` can be used to show all video file's  preview thumbnail.

**Comment by MiTereKun** [comment]
That's why I wrote that "WebP" is already outdated, but at least it is contained in modern operating systems and can be opened without problems. And those who know about the way of cyclic playback  of mp4 can be counted on the finger of the hand. Well, unfortunately, the global rejection of the new is a natural couple of all people, and that is why we still have not departed from the formats of the last century: jpg, png and gif

**Comment by Ahaochan** [comment]
The limitations of UserScript prevent me from generating mp4 format using ffmpeg.
