### ISSUE TITLE
无法显示图片尺寸和替换原图

### ISSUE THREAD

**Issue by E1SA-ux** [Ahaochan/Tampermonkey#74]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [X] [Chrome](https://www.google.com/chrome/)
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [X] [Tampermonkey](https://tampermonkey.net/)
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [X] 我确认除了此脚本外, 其他任意脚本能正常运行
- [X] 我确认此脚本是最新版本
- [X] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
在所有图片右上角显示图片尺寸。 单张图片: 替换成原图, 拖拽到桌面进行保存
### 实际行为 
无显示尺寸，也无替换成原图

### 重现步骤 
1. 
2. 
3.

**Comment by Edge-coordinates** [comment]
是这样的，图片现在不能现实分辨率而且也不能更新，期待作者的新版本，感谢！
