### ISSUE TITLE
自动加载评论失效

### ISSUE THREAD

**Issue by yuijker** [Ahaochan/Tampermonkey#76]
### 基本信息 

- 版本号: 
- 所用浏览器及版本号: 
  - [x] [Chrome](https://www.google.com/chrome/) 106.0.5249.62
  - [] [Firefox](https://www.mozilla.org/en-US/)
  - [] Other  
- 插件扩展: 
  - [x] [Tampermonkey](https://tampermonkey.net/) 4.16.1
  - [] [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)
  - [] [Violentmonkey](https://violentmonkey.github.io/get-it/)

### 我确认我已经完成以下步骤 

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅[GreasyFork](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus/feedback)的反馈区, 以及GitHub的[Issue](https://github.com/Ahaochan/Tampermonkey/issues), 均未发现相似问题

### 预期行为 
开启自动加载评论后，作品下的评论会自动向下加载

### 实际行为 
即使开启自动加载评论后，作品下的评论也不会自动向下加载

### 重现步骤 
1. 安装脚本
2. 来到pixiv的设置页，来确认该功能是否开启
3. 打开一个作品页面，看到评论没有自动加载

### 其他信息 

![image](https://user-images.githubusercontent.com/72558803/195085791-3c657aed-5ffa-4edc-a32f-917d3760f747.png)

![image](https://user-images.githubusercontent.com/72558803/195085882-fe459b28-14fe-46ed-a6be-a21f546cb506.png)

**Comment by Ahaochan** [comment]
https://github.com/Ahaochan/Tampermonkey/issues/79
