### ISSUE TITLE
fuck天猫脚本失效了

### ISSUE THREAD

**Issue by whyjxz14** [Ahaochan/Tampermonkey#78]
RT

**Comment by whc2001** [comment]
tb 更新了最新的网页端之后好像就挂了，现在标题前面所有的小图标不论有几个全部变成了一张图，如下图所示

![image](https://github.com/Ahaochan/Tampermonkey/assets/16266909/59546109-627b-4313-964d-03ab98c17e07)
![image](https://github.com/Ahaochan/Tampermonkey/assets/16266909/364419ef-7e81-4a0f-a3a8-315f69622eff)
![image](https://github.com/Ahaochan/Tampermonkey/assets/16266909/f249046e-3e5d-45cb-a2aa-519b0803a11a)

目前个人在使用的对策是寻找所有类名以 `Title--iconPic--` 打头的图片，然后向上找类名以 `Card--doubleCardWrapper--` 打头的 `div` 进行删除，但缺点是参与活动的非天猫店（如图三）也会被过滤，需要酌情手动控制脚本开关

```js
(function ($) {
    'use strict';
    setInterval(function () {
        $("img[class^='Title--iconPic--']").each(function() {
            $(this).parents().each(function() {
                if (this.className.startsWith('Card--doubleCardWrapper--')) {
                    $(this).remove();
                    return false;
                }
            });
        });
    }, 1000);
})(jQuery);
```

效果如图：

![image](https://github.com/Ahaochan/Tampermonkey/assets/16266909/3dcae2ce-0723-4e4f-b90c-773c78f2e015)

**Comment by whc2001** [comment]
今天突然意识到 `Card--doubleCardWrapper--XXX` 这个元素是个 `a`，并且但凡是天猫商品链接一定是天猫域名，改进一下：

```js
(function ($) {
    'use strict';
    setInterval(function () {
        $("img[class^='Title--iconPic--']").each(function() {
            $(this).parents().each(function() {
                if (this.className.startsWith('Card--doubleCardWrapper--') && this.href.includes(".tmall.com")) {
                    $(this).parent().hide();
                    $(this).remove();
                    return false;
                }
            });
        });
    }, 1000);
})(jQuery);
```
