### ISSUE TITLE
往下拖动后的图片保存在哪里呢

### ISSUE THREAD

**Issue by 7um** [Ahaochan/Tampermonkey#8]
下拉拖动(Dev Only)后的图片保存在哪里了呢，可能是没有保存，出现了bug

**Comment by Ahaochan** [comment]
具体是哪个脚本？请填写以下信息。方便了解细节。



### 脚本的名称及greasyfork链接
- 名称:
- greasyfork链接:

### 我确认我已经完成以下步骤

- [] 我确认除了此脚本外, 其他任意脚本能正常运行
- [] 我确认此脚本是最新版本
- [] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均为发现相似问题

### 预期行为


### 实际行为


### 重现步骤
1. 
2. 
3. 

### 其他信息

**Comment by 7um** [comment]
已经可以使用，谢谢您的负责及诚意
________________________________
发件人: Ahaochan <notifications@github.com>
发送时间: 2018年3月15日 23:06
收件人: Ahaochan/Tampermonkey
抄送: 7um; Author
主题: Re: [Ahaochan/Tampermonkey] 往下拖动后的图片保存在哪里呢 (#8)


具体是哪个脚本？请填写以下信息。方便了解细节。

脚本的名称及greasyfork链接

  *   名称:
  *   greasyfork链接:

我确认我已经完成以下步骤

  *   [] 我确认除了此脚本外, 其他任意脚本能正常运行
  *   [] 我确认此脚本是最新版本
  *   [] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均为发现相似问题

预期行为
实际行为
重现步骤

  1.
  2.
  3.

其他信息

―
