### ISSUE TITLE
Popular Pictures Sort Not working

### ISSUE THREAD

**Issue by Yoposoc** [Ahaochan/Tampermonkey#9]
### 脚本的名称及greasyfork链接
- 名称: Pixiv Plus
- greasyfork链接: https://greasyfork.org/en/scripts/34153-pixiv-plus

### 我确认我已经完成以下步骤

- [x] 我确认除了此脚本外, 其他任意脚本能正常运行
- [x] 我确认此脚本是最新版本
- [x] 我确认已经翻阅greasyfork的反馈区, 以及github的issue, 均为发现相似问题

### 预期行为
Thank you for making this script. It is very helpful.
I noticed sorting by "popular pictures" is not working.
What is the expected behavior?

I am not using greasemonkey. I am using violentmonkey with Waterfox. Violentmonkey should be almost the same as greasemonkey.

**Comment by Ahaochan** [comment]
My Pixiv Plus script does not support  **sorting**.
I will add a single page sorting feature in the next version.

If you mean to use **1000users入り** way to sort.
It can only filter pictures with a number of **users入り** above 1000, and cannot be sorted.

![image](https://user-images.githubusercontent.com/17980786/40277162-4a766d16-5c4d-11e8-9f7c-e8e4dc0a36fc.png)

**Comment by Yoposoc** [comment]
I see.
Does:
2. View popular pictures. 
mean "automatically and quickly use XXXXusers入り as a search term?"

If so, it may be better to say "Quickly view popular pictures by using XXXXusers入り keywords." It is slightly misleading currently.
